package dynview

DYNVIEW_INVALIDATE_CONTENT :: (1 << 0)
DYNVIEW_INVALIDATE_PANEL :: (1 << 1)
DYNVIEW_INVALIDATE_FONT :: (1 << 2)
DYNVIEW_INVALIDATE_STYLE :: (1 << 3)

DYNVIEW_ENABLED_DEFAULT :: true

