name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Setup julia for build support
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.8

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build Julia bits
      run: |
        julia AddPackages.jl
        julia ElementsBook1/build_notebooks.jl
      shell: bash

    - name: Build Javascript bits
      run: |
        npm install
        npx webpack
