name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Pull & update submodules recursively
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote

    #- name: Setup julia for build support
    #  uses: julia-actions/setup-julia@v1
    #  with:
    #    version: 1.8

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    #- name: Add Julia Packages
    #  run: |
    #    julia AddPackages.jl
    #  shell: bash

    #- name: Build Julia bits
    #  run: |
    #    julia ElementsBook1/build_notebooks.jl
    #  shell: bash

    - name: Build Javascript bits
      run: |
        npm install
        npx webpack

    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with:
        name: assets-for-download
        path: build/dist
