name: Build and Deploy Webpage Version to GitHub Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: build-github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Pull & update submodules recursively
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote

    #- name: Setup julia for build support
    #  uses: julia-actions/setup-julia@v1
    #  with:
    #    version: 1.8

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    #- name: Add Julia Packages
    #  run: |
    #    julia AddPackages.jl
    #  shell: bash

    #- name: Build Julia bits
    #  run: |
    #    julia ElementsBook1/build_notebooks.jl
    #  shell: bash

    - name: Build Javascript bits
      run: |
        npm install
        npx webpack


    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload entire repository
        path: './build/dist/'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
